title: "Go（GORM&Echo）でAPIを作る（初学者向け）"
summary: "foo"
topics: ["go", "API", "GORM", "Echo", "MySQL"]
published: false
price: 500
chapters:
  - intro
  - go-install-setup
  - gorm-install-create-database
  - gorm-migrate
  - godotenv
  - echo-setup
  - organize
  - crud-create
  - crud-read
  - crud-update
  - crud-delete
  - separate-controller-model
  - crud-update-todo-status
